stages:
  - test
  - deploy
test_stage:
  stage: test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - ./manage.py test
deploy_stage:
  stage: deploy
  script:
    - echo "The project was deployed"  