stages:
  - test

variables:
  # Docker image for the pipeline
  PYTHON_VERSION: "3.9"
  DJANGO_SETTINGS_MODULE: "yourproject.settings.production"  # Adjust for your settings structure
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Test stage
test:
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - python manage.py check
    - python manage.py test
  only:
    - merge_requests
    - master
    - main

