stages:
  - build
  - test
  - deploy

build_stage:
  stage: build
  script:
    - echo "You are in build stage"
quality_stage:
  stage: test
  script:
    - echo "You are in quality stage"
deploy_stage:
  stage: deploy
  script:
    - echo "You are in deploy stage"

