# Generated by Django 5.1.7 on 2025-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
