# Generated by Django 5.1.7 on 2025-05-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_default',
        ),
    ]
